---
- hosts: all
  become: yes
  become_user: root
  vars_prompt:
    - name: user_name
      prompt: "Enter the user name:"
      private: no
    - name: user_password
      prompt: "Enter the user password:"
      private: yes

  tasks:
  - name: Create user
    users:
      name: "{{ user_name }}"
      state: present
      password: "{{ user_password }}"
      groups: sudo

  - name: Create drop-in sudoers file
    file:
      path: /etc/sudoers.d/{{ user_name }}
      state: touch
      owner: root
      group: root
      mode: 0440

  - name: Add sudoer entry
    sudoers:
      name: "{{ user_name }}"
      state: present
      file: /etc/sudoers.d/{{ user_name }}
      nopasswd: yes
      runas: ALL

  - name: Add public key to authorized keys file
     authorized_key:
       key: "{{ lookup('file', '/path/to/public_key') }}"
       user: "{{ user_name }}"
       state: present
       key_options: ssh-rsa