---
- hosts: all
  become: yes
  become_user: root
  vars_prompt:
    - name: user_name
      prompt: "Enter the user name:"
      private: no
    - name: user_password
      prompt: "Enter the user password:"
      private: yes

  tasks:
  - name: Create user
    users:
      name: "{{ user_name }}"
      state: present
      password: "{{ user_password }}"
      groups: sudo
      create_home: true

  - name: Create drop-in sudoers file
    file:
      path: /etc/sudoers.d/{{ user_name }}
      state: touch
      owner: root
      group: root
      mode: 0440

  - name: Add sudoer entry
    sudoers:
      name: "{{ user_name }}"
      state: present
      file: /etc/sudoers.d/{{ user_name }}
      nopasswd: yes
      runas: ALL

  - name: create .ssh if it does not exist
    file:
      path: /home/{{ user_name }}/.ssh
      state: directory
      mode: '0700'

  - name: copy authorized_keys file
    copy:
      src: $PWD/sshkey/authorized_keys
      dest: /home/{{ user_name }}/.ssh/authorized_keys
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0600'
      backup: yes

