## Playbook that creates a user for ansible, and sets password, and then copies authorized keys file in to place
# run with: ansible-playbook playbooks/getReadyForAnsible-v2.yml --limit="NewServerThatNeedsToBeSetUp" --ask-vault-pass -kK

---
- name: Get new server ready for use with ansible
  hosts: all
  become: true
  become_user: root
  remote_user: ramiraz
  vars_files:
    - ../vars/vars-file.yml

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
        groups: wheel
        create_home: true

    - name: Create drop-in sudoers file
      ansible.builtin.file:
        path: /etc/sudoers.d/{{ user_name }}
        state: touch
        owner: root
        group: root
        mode: 0440

    - name: add line in sudoers file
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ user_name }}
        state: present
        line: '{{ user_name }} ALL=(ALL) NOPASSWD:ALL'

    - name: create .ssh if it does not exist
      ansible.builtin.file:
        path: /home/{{ user_name }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: copy authorized_keys file
      ansible.builtin.copy:
        src: authorized_keys
        dest: /home/{{ user_name }}/.ssh/authorized_keys
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
        backup: true
